name: Build for cPanel

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Enable pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build app
        run: pnpm build

      - name: Copy public and static files
        run: |
          cp -r public .next/standalone/public
          cp -r .next/static .next/standalone/.next/static

      - name: Zip cPanel build
        run: |
          cd .next/standalone
          zip -r ../../mix-streamer-cpanel.zip .

      - name: Upload build file
        uses: actions/upload-artifact@v4
        with:
          name: mix-streamer-cpanel
          path: mix-streamer-cpanel.zip
